services:
  metrics_server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 50s
      timeout: 5s
      retries: 3
      start_period: 10s
